### ISSUE TITLE
ArcEngine Internal Error - value of 'null' is not valid for 'stream'

### ISSUE THREAD

**Issue by WeirdBeardDev** [WeirdBeardDev/dungeoneye#1]
An ArcEngine exception provided this:

at System.Drawing.Icon..ctor(Stream stream, Int32 width, Int32 height)
at DungeonEye.Game.LoadContent() in C:\GitHub\dungeoneye\DungeonEye.cs:line 133
at ArcEngine.GameBase.Run() in C:\GitHub\arcengine\Framework\GameBase.cs:line 491

**Comment by WeirdBeardDev** [comment]
Fixed once I changed the data/Game.bnk file's Build Action to Content and Copy to Output Directory - Copy if newer.
